name: gmailAPI
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohttp=3.8.3=py310h90acd4f_1
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=22.2.0=pyh71513ae_0
  - blas=2.116=openblas
  - blas-devel=3.9.0=16_osx64_openblas
  - blinker=1.5=pyhd8ed1ab_0
  - brotlipy=0.7.0=py310h90acd4f_1005
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2022.12.7=h033912b_0
  - cachetools=5.2.1=pyhd8ed1ab_0
  - cairo=1.16.0=h0ab9d94_1001
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py310ha78151a_3
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - cryptography=39.0.0=py310h23bb4e6_0
  - eigen=3.4.0=h940c156_0
  - fontconfig=2.13.94=h10f422b_0
  - freetype=2.10.4=h4cff582_1
  - frozenlist=1.3.3=py310h90acd4f_0
  - gettext=0.21.1=h8a4c099_0
  - giflib=5.2.1=hbcb3906_2
  - glib=2.69.1=hfff2838_2
  - google-api-core=2.10.1=pyhd8ed1ab_0
  - google-api-python-client=2.72.0=pyhd8ed1ab_0
  - google-auth=2.15.0=pyh1a96a4e_0
  - google-auth-httplib2=0.1.0=pyhd8ed1ab_1
  - google-auth-oauthlib=0.8.0=pyhd8ed1ab_0
  - googleapis-common-protos=1.57.0=py310h2ec42d9_0
  - graphite2=1.3.14=he9d5cce_1
  - gst-plugins-base=1.14.0=h4180768_2
  - gstreamer=1.14.0=h0fc69c2_2
  - harfbuzz=4.3.0=h3f129a2_0
  - hdf5=1.10.6=h10fe05b_1
  - httplib2=0.21.0=pyhd8ed1ab_0
  - icu=58.2=h0a44026_1000
  - idna=3.4=pyhd8ed1ab_0
  - jpeg=9e=hac89ed1_2
  - krb5=1.19.3=hb49756b_0
  - lerc=3.0=he9d5cce_0
  - libblas=3.9.0=16_osx64_openblas
  - libcblas=3.9.0=16_osx64_openblas
  - libclang=12.0.0=default_hbc2896b_2
  - libcxx=14.0.6=hccf4f1f_0
  - libdeflate=1.8=h9ed2024_5
  - libedit=3.1.20191231=h0678c8f_2
  - libffi=3.4.2=hecd8cb5_6
  - libgfortran=5.0.0=11_3_0_h97931a8_27
  - libgfortran5=11.3.0=h082f757_27
  - libiconv=1.17=hac89ed1_0
  - liblapack=3.9.0=16_osx64_openblas
  - liblapacke=3.9.0=16_osx64_openblas
  - libllvm12=12.0.1=hd011deb_2
  - libopenblas=0.3.21=openmp_h429af6e_3
  - libpng=1.6.37=ha441bb4_0
  - libpq=12.9=h1c9f633_3
  - libprotobuf=3.20.1=h8346a28_0
  - libtiff=4.4.0=h2cd0358_2
  - libwebp=1.2.4=hfa4350a_0
  - libwebp-base=1.2.4=h775f41a_0
  - libxml2=2.9.14=hbf8cd5e_0
  - libxslt=1.1.35=h5b33f42_0
  - llvm-openmp=15.0.7=h61d9ccf_0
  - lz4-c=1.9.3=he49afe7_1
  - multidict=6.0.4=py310h90acd4f_0
  - ncurses=6.3=hca72f7f_3
  - nspr=4.35=hea0b92c_0
  - nss=3.74=h47edf6a_0
  - numpy=1.24.1=py310h1b7c290_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openblas=0.3.21=openmp_hbefa662_3
  - opencv=4.6.0=py310haf7406c_2
  - openjpeg=2.3.1=h6cbf5cd_3
  - openssl=1.1.1s=hfd90126_1
  - pandas=1.5.2=py310hecf8f37_2
  - pcre=8.45=he49afe7_0
  - pip=22.3.1=py310hecd8cb5_0
  - pixman=0.38.0=h01d97ff_1003
  - protobuf=3.20.1=py310he9d5cce_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyjwt=2.6.0=pyhd8ed1ab_0
  - pyopenssl=23.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.8=h218abb5_1
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2022.7=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - qt-main=5.15.2=h719ae48_7
  - qt-webengine=5.15.9=h90a370e_4
  - qtwebkit=5.212=h24dc246_4
  - readline=8.2=hca72f7f_0
  - requests=2.28.1=pyhd8ed1ab_1
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - setuptools=65.6.3=py310hecd8cb5_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.40.1=h880c91c_0
  - tk=8.6.12=h5d9f67b_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022g=h04d1e81_0
  - uritemplate=4.1.1=pyhd8ed1ab_0
  - urllib3=1.26.14=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.8=h6c40b1e_0
  - yarl=1.8.2=py310h90acd4f_0
  - zlib=1.2.13=h4dc903c_0
  - zstd=1.5.2=hcb37349_0
prefix: /Users/drysdaleerik/miniconda3/envs/gmailAPI
